server:
  port: 9999

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///managementdb

  redis:
    port: 6379
    host: localhost

logging:
  level:
    com.usermanagementsystem.management: debug
